version: '3.9'
services:
  SquidProxy:
    ports:
      - "3128:3128"
    image: "squidproxy"
    volumes:
      - type: bind
        source: /home/oplexadmin/squidlex/logs/access.log
        target: /var/log/squid/access.log
      - type: bind
        source: /home/oplexadmin/squidlex/cache/cache.log
        target: /var/log/squid/cache.log
      - type: bind
        source: /home/oplexadmin/squidlex/squidguard/squidguard.conf
        target: /etc/squidguard/squidGuard.conf
      - type: bind
        source: /home/oplexadmin/squidlex/squid/squid.conf
        target: /etc/squid/squid.conf
    container_name: SquidProxy
    restart: always
    environment:
      - REDIRECT_URL=https://www.google.com
